sticky_side: 1
animations_state: 1
banner_background_color: region--default-background
banner_blocks_paddings: 1
banner_id: banner
banner_layout_container: container-fluid
banner_region_paddings: 1
bootstrap_remote_type: cdn
breadcrumb_separator: fa-angle-right
breaking_effect: fade
breaking_effect_time: '5'
color_scheme: green
global_corner_style: mt-style-rounded
button_corner_style: mt-style-button-rounded
form_corner_style: mt-style-form-rounded
image_corner_style: mt-style-image-rounded
menu_corner_style: mt-style-menu-rounded
custom_elements_corner_style: mt-style-custom-rounded
links_style: mt-link-style-animated-icon-2
content_bottom_animation_effect: fadeInUp
content_bottom_background_color: region--accent-background
content_bottom_blocks_paddings: 0
content_bottom_id: content-bottom
content_bottom_layout_container: container
content_bottom_region_paddings: 0
content_bottom_separator: region--no-separator
content_top_animation_effect: fadeInLeft
content_top_background_color: region--default-background
content_top_blocks_paddings: 0
content_top_highlighted_animation_effect: fadeInRight
content_top_highlighted_background_color: region--default-background
content_top_highlighted_blocks_paddings: 0
content_top_highlighted_id: content-top-highlighted
content_top_highlighted_layout_container: container
content_top_highlighted_region_paddings: 1
content_top_highlighted_separator: region--no-separator
content_bottom_highlighted_animation_effect: fadeInDown
content_bottom_highlighted_background_color: region--default-background
content_bottom_highlighted_blocks_paddings: 0
content_bottom_highlighted_id: content-bottom-highlighted
content_bottom_highlighted_layout_container: container
content_bottom_highlighted_region_paddings: 1
content_bottom_highlighted_separator: region--no-separator
content_top_id: content-top
content_top_layout_container: container
content_top_region_paddings: 0
featured_animation_effect: fadeInUp
featured_background_color: region--colored-background
featured_blocks_paddings: 1
featured_bottom_animation_effect: fadeInLeft
featured_bottom_background_color: region--default-background
featured_bottom_blocks_paddings: 0
featured_bottom_id: featured-bottom
featured_bottom_layout_container: container-fluid
featured_bottom_region_paddings: 0
featured_bottom_separator: region--no-separator
featured_id: featured
featured_layout_container: container
featured_region_paddings: 0
featured_separator: region--no-separator
featured_top_animation_effect: fadeInDown
featured_top_background_color: region--accent-background
featured_top_blocks_paddings: 0
featured_top_id: featured-top
featured_top_layout_container: container
featured_top_region_paddings: 0
featured_top_separator: region--no-separator
fixed_header: 1
fixed_header_behavior: fixed-header-enabled--scroll-up
font_resize: 1
footer_animation_effect: fadeInRight
footer_background_color: region--colored-background
footer_blocks_paddings: 0
footer_bottom_background_color: region--colored-background
footer_bottom_blocks_paddings: 0
footer_bottom_id: footer-bottom
footer_bottom_layout_container: container
footer_bottom_region_paddings: 0
footer_bottom_separator: region--no-separator
footer_id: footer
footer_layout_container: container
footer_region_paddings: 0
footer_separator: region--no-separator
footer_top_animation_effect: fadeInLeft
footer_top_background_color: region--default-background
footer_top_blocks_paddings: 0
footer_top_id: footer-top
footer_top_layout_container: container
footer_top_region_paddings: 0
footer_top_separator: region--no-separator
hero_top_animation_effect: fadeInUp
hero_top_background_color: region--colored-background
hero_top_blocks_paddings: 0
hero_top_id: hero-top
hero_top_layout_container: container
hero_top_region_paddings: 0
hero_animation_effect: fadeInUp
hero_background_color: region--default-background
hero_blocks_paddings: 1
hero_id: hero
hero_layout_container: container
hero_region_paddings: 1
sticky_footer_layout_container: container
sticky_footer_background_color: region--default-background
sticky_footer_blocks_paddings: 0
sticky_footer_region_paddings: 0
sticky_footer_trigger_text: ''
google_maps_key: AIzaSyDyL-4KyWw_3hp-0jmZLGcJ3zMWkkJ44VI
header_background_color: region--default-background
header_background_image_state: 0
header_blocks_paddings: 0
header_layout_container: container
header_region_paddings: 1
header_top_animation_effect: fadeInDown
header_top_background_color: region--accent-background
header_top_blocks_paddings: 0
header_top_highlighted_animation_effect: fadeInDown
header_top_highlighted_background_color: region--accent-background
header_top_highlighted_blocks_paddings: 0
header_top_highlighted_layout_container: container
header_top_highlighted_region_paddings: 1
header_top_layout_container: container
header_top_region_paddings: 0
headings_font_family: hff-39
headings_wide_spacing: 0
highlighted_animation_effect: fadeInUp
highlighted_background_color: region--default-background
highlighted_blocks_paddings: 0
highlighted_id: highlighted
highlighted_layout_container: container
highlighted_region_paddings: 0
highlighted_separator: region--no-separator
highlighted_top_animation_effect: fadeInDown
highlighted_top_background_color: region--accent-background
highlighted_top_blocks_paddings: 0
highlighted_top_id: highlighted-top
highlighted_top_layout_container: container
highlighted_top_region_paddings: 0
highlighted_top_separator: region--no-separator
in_page_navigation_offset: '69'
in_page_slider_effect: fade
flexslider_main_effect: fade
flexslider_main_effect_time: '5'
inverted_header_state: 0
isotope_filters_text: All
isotope_layout_mode: fitRows
layout_mode: wide
main_content_layout_container: container
main_content_animation_effect: fadeInUp
main_content_blocks_paddings: 0
main_content_id: main-content
main_content_region_paddings: 0
main_content_separator: region--no-separator
main_content_background_color: region--default-background
owl_albums_autoplay: 1
owl_albums_effect_time: '5'
owl_articles_autoplay: 1
owl_articles_effect_time: '5'
owl_collections_autoplay: 0
owl_collections_effect_time: '5'
owl_products_autoplay: 1
owl_products_effect_time: '5'
owl_promoted_posts_autoplay: false
owl_promoted_posts_effect_time: '5'
owl_related_nodes_autoplay: 0
owl_related_nodes_effect_time: '5'
owl_team_members_autoplay: 1
owl_team_members_effect_time: '5'
owl_testimonials_autoplay: 1
owl_testimonials_effect_time: '5'
page_container_border: 0
paragraph_font_family: pff-03
paragraph_responsive_typography: 1
post_progress: 1
print_button: 1
reading_time: 1
rs_slideshow_background_opacity: '50'
rs_slideshow_boxedwidth_bullets_position: center
rs_slideshow_boxedwidth_effect: random
rs_slideshow_boxedwidth_effect_time: '10'
rs_slideshow_boxedwidth_initial_height: '500'
rs_slideshow_boxedwidth_auto_height: 0
rs_slideshow_boxedwidth_navigation_style: bullets
rs_slideshow_boxedwidth_touch_swipe: 1
rs_slideshow_caption_opacity: '0'
rs_slideshow_fullscreen_bullets_position: right
rs_slideshow_fullscreen_effect: random
rs_slideshow_fullscreen_effect_time: '10'
rs_slideshow_fullscreen_navigation_style: bullets
rs_slideshow_fullscreen_touch_swipe: 1
rs_slideshow_fullwidth_bullets_position: right
rs_slideshow_fullwidth_effect: random
rs_slideshow_fullwidth_effect_time: '10'
rs_slideshow_fullwidth_initial_height: '500'
rs_slideshow_fullwidth_auto_height: 0
rs_slideshow_fullwidth_navigation_style: bullets
rs_slideshow_fullwidth_touch_swipe: 1
rs_slideshow_internal_banner_bullets_position: left
rs_slideshow_internal_bullets_position: left
rs_slideshow_internal_carousel_bullets_position: center
rs_slideshow_internal_carousel_effect: fade
rs_slideshow_internal_carousel_initial_height: '540'
rs_slideshow_internal_carousel_touch_swipe: 1
rs_slideshow_internal_effect: fade
rs_slideshow_internal_effect_time: '10'
rs_slideshow_internal_initial_height: '450'
rs_slideshow_internal_auto_height: 0
rs_slideshow_internal_navigation_style: bullets
rs_slideshow_internal_touch_swipe: 1
scroll_to_top_display: 1
scroll_to_top_icon: fa-angle-double-up
share_links: 1
share_links_print_position: bottom
sidebar_first_animation_effect: fadeInLeft
sidebar_first_blocks_paddings: 0
sidebar_first_region_paddings: 0
sidebar_second_animation_effect: fadeInRight
sidebar_second_blocks_paddings: 0
sidebar_second_region_paddings: 0
sitename_font_family: sff-39
slideout_background_color: region--default-background
slideout_mobile_menu_display: 0
slideout_blocks_paddings: 0
slideout_region_paddings: 0
slideout_side: right
slideout_touch_swipe: 0
slogan_font_family: slff-39
sub_featured_animation_effect: fadeInRight
sub_featured_background_color: region--accent-background
sub_featured_blocks_paddings: 0
sub_featured_id: sub-featured
sub_featured_layout_container: container
sub_featured_region_paddings: 0
sub_featured_separator: region--no-separator
subfooter_background_color: region--colored-background
subfooter_blocks_paddings: 0
subfooter_bottom_blocks_paddings: false
subfooter_bottom_region_paddings: false
subfooter_id: subfooter
subfooter_layout_container: container
subfooter_region_paddings: 0
subfooter_separator: region--no-separator
subfooter_top_background_color: region--default-background
subfooter_top_blocks_paddings: 0
subfooter_top_id: subfooter-top
subfooter_top_layout_container: container
subfooter_top_region_paddings: 0
subfooter_top_separator: region--no-separator
transparent_header_opacity: '0'
transparent_header_state: 0
total_node_views: 1
purechat_key: ''
purechat_display: 0
mobile_menu_widget_display: 1
mobile_menu_widget_sticky: 1
rs_slideshow_internal_layout: fullscreen
header_horizontal_paddings: 1
enable_pwa: 0
_core:
  default_config_hash: hXjMFpsnNS4pLfk3pVaOB8dWlwH_gIkBdpV5vZ8Ba2c
langcode: fr
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://logo.png'
favicon:
  use_default: false
  path: 'public://favicon.png'
  mimetype: image/png
font_title: ''
