multiple_registration_hidden_point_focal: 1
multiple_registration_form_mode_register_point_focal: point_focal
multiple_registration_form_mode_edit_point_focal: point_focal
multiple_registration_hidden_acteur: 1
multiple_registration_form_mode_register_acteur: register
multiple_registration_form_mode_edit_acteur: acteur
multiple_registration_hidden_expert: 1
multiple_registration_form_mode_register_expert: register
multiple_registration_form_mode_edit_expert: expert
multiple_registration_path_point_focal: inscription/point-focal
multiple_registration_url_point_focal: /user/register/point_focal
multiple_registration_path_acteur: inscription/acteur
multiple_registration_url_acteur: /user/register/acteur
multiple_registration_path_expert: inscription/expert
multiple_registration_url_expert: /user/register/expert
