ui_localtask: true
ui_checkbox: false
create_revision: false
create_log_entry: true
publish_text_value: Publier
unpublish_text_value: Dépublier
_core:
  default_config_hash: yrqqG88pLjv5VOMc9Mp665VJUyK4lMCZwg8376pI0SQ
langcode: fr
