<?php

/**
 * @file
 * Contains user_approval_dashboard.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_approval_dashboard_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_approval_dashboard module.
    case 'help.page.user_approval_dashboard':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to approve users.') . '</p>';
      return $output;

    default:
  }
}
